- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  become: yes
  when: installed_jenkins.changed

- name: wait for jenkins to shut down
  pause:
    seconds: 2

- name: wait for jenkins to start up
  uri:
    url: "http://localhost:8080/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1